on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string

jobs:
  build-gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle Wrapper
        run: ./gradlew build -x test
      - name: Rename artifact
        run: mv build/libs/*.jar build/libs/${{ inputs.artifact-name }}.jar
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: binchae-be
          path: build/libs/${{ inputs.artifact-name }}.jar