on:
  workflow_call:
    inputs:
      application-name:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
      identifier:
        required: true
        type: string
    secrets:
      AWS_CODE_DEPLOY_GROUP_NAME:
        required: true
      AWS_S3_BUCKET_NAME:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true

jobs:
  create-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create a new deployment
        run: aws deploy create-deployment --application-name ${{ inputs.application-name }} --s3-location bucket=${{ secrets.AWS_S3_BUCKET_NAME }},key=${{ inputs.artifact-name }}-${{ inputs.identifier }}.zip,bundleType=zip --deployment-group-name ${{ secrets.AWS_CODE_DEPLOY_GROUP_NAME }} --deployment-config-name CodeDeployDefault.AllAtOnce