on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd && ls -al
  build:
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: binchae-be
    needs: checkout
  end:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: binchae-be
          path: ./artifacts
      - run: ls -al ./artifacts
