on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd && ls -al
  build:
    uses: ./.github/workflows/build.yml
    needs: checkout
  end:
    runs-on: ubuntu-latest
    steps:
      - run: ls ${{ github.workspace }} -al
