on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      clean_build:
        description: 'Perform a clean build'
        required: false
        default: 'false'

jobs:
  test:
    uses: ./.github/workflows/test-gradle.yml
  build:
    uses: ./.github/workflows/build-gradle-artifact.yml
    with:
      artifact-name: binchae-be
    needs: test
  end:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Print test result
        uses: actions/download-artifact@v2
        with:
          name: test-result
          path: ./test
      - run: cat ./test/test-result.txt
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: binchae-be
          path: ./artifacts
      - run: ls -al ./artifacts

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run application
        run: java -jar ./artifacts/binchae-be.jar
