on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
  build:
    uses: ./.github/workflows/build.yml
    with:
      gradle-path: ${{ github.workspace }}
    needs: checkout
  end:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.workspace }}
