on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build with reusable action
        uses: altair823/GithubActionTest/.github/workflows/build.yaml
      - name: post-job
        run: echo "post-job"
