on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      identifier:
        required: true
        type: string
    secrets:
      AWS_S3_BUCKET_NAME:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true


jobs:
  upload-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./artifacts

      - name: Move scripts to artifact directory
        run: mv ./scripts ./artifacts

      - name: Move appspec to artifact directory
        run: mv ./appspec.yml ./artifacts

      - name: Zip artifact and scripts
        run: zip -r ${{ inputs.artifact-name }}.zip ./artifacts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload zip to S3
        run: aws s3 cp ${{ inputs.artifact-name }}.zip s3://${{ secrets.AWS_S3_BUCKET_NAME }}/${{ inputs.identifier }}/${{ inputs.artifact-name }}.zip

